# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151210001204 on 2015-12-25 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.TextField()),
                ('header', models.ImageField(upload_to='images/header')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
