# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151210001204 on 2015-12-25 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='header',
        ),
    ]
