# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151210001204 on 2015-12-25 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_remove_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.ImageField(default=datetime.datetime(2015, 12, 25, 2, 40, 58, 73330, tzinfo=utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
