# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:29
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.ImageField(upload_to=Projects.models.get_upload_file_name),
        ),
    ]
