# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 19:37
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20160111_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tumbnail',
            field=models.ImageField(blank=True, upload_to=Projects.models.get_upload_thumbnail_name),
        ),
        migrations.AlterField(
            model_name='project',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.ImageField(blank=True, upload_to=Projects.models.get_upload_file_name),
        ),
    ]
