# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 05:00
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20160207_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('project_hook', models.IntegerField()),
                ('sort_index', models.IntegerField(blank=True, default=1)),
                ('image_visibility', models.BooleanField()),
                ('image', models.FileField(blank=True, upload_to=Projects.models.get_upload_file_name)),
                ('discription', models.TextField(blank=True)),
                ('code_visibility', models.BooleanField()),
                ('type_of_code', models.CharField(choices=[('javascript', 'javascript'), ('markup', 'markup'), ('css', 'css'), ('php', 'php'), ('python', 'python')], default='markup', max_length=20)),
                ('pre_block', models.TextField(blank=True)),
                ('code_block', models.TextField(blank=True)),
                ('post_block', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.FileField(blank=True, upload_to=Projects.models.get_upload_file_name),
        ),
    ]
