# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 22:18
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0026_auto_20160209_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='addon_video',
            field=models.FileField(blank=True, upload_to=Projects.models.get_upload_video_name),
        ),
        migrations.AddField(
            model_name='addon',
            name='post_video_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='pre_video_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='video_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='header',
            field=models.FileField(blank=True, upload_to=Projects.models.get_upload_file_name),
        ),
    ]
