# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 22:20
from __future__ import unicode_literals

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0027_auto_20160210_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.FileField(blank=True, upload_to=Projects.models.get_upload_addon_file_name),
        ),
    ]
