# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
