# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_professionalexperience_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduate_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='education',
            name='graduate_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April '), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='education',
            name='graduate_year',
            field=models.IntegerField(blank=True, default=2007),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April '), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='end_year',
            field=models.IntegerField(blank=True, default=2007),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='start_year',
            field=models.IntegerField(blank=True, default=2007),
        ),
    ]
