# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_auto_20160208_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.CharField(max_length=500),
        ),
    ]
