# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_auto_20160209_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='graduate_date',
        ),
    ]
