# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_professional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='professional_experience',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
