# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_remove_education_graduate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
