# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_auto_20160208_0633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professional_Experience',
            new_name='ProfessionalExperience',
        ),
    ]
