# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_auto_20160208_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('school_name', models.CharField(blank=True, max_length=500)),
                ('graduate_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
    ]
