# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='discription_4',
        ),
    ]
