# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addon', '0002_remove_addon_discription_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='discription_4',
            field=models.TextField(blank=True),
        ),
    ]
