# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 04:45
from __future__ import unicode_literals

import Addon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addon', '0003_addon_discription_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=Addon.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='addon',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=Addon.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='addon',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=Addon.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='addon',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=Addon.models.get_upload_file_name),
        ),
    ]
