# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addon', '0004_auto_20160127_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='sort_index',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
