# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 17:11
from __future__ import unicode_literals

import Addon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addon', '0006_auto_20160130_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.FileField(blank=True, upload_to=Addon.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='addon',
            name='type_of_code',
            field=models.CharField(choices=[('javascript', 'javascript'), ('markup', 'markup'), ('css', 'css'), ('php', 'php'), ('python', 'python')], default='markup', max_length=20),
        ),
    ]
